### ISSUE TITLE
Subtlety

### ISSUE THREAD

**Issue by davecastlevania** [jessorellanes/colmar-academy#2]
https://github.com/jessorellanes/colmar-academy/blob/master/resources/css/style.css#L1-L444

You should consider cleaning up your code using a tool like [DirtyMarkup](https://dirtymarkup.com/) or using the `Atom-Beautify` package for the Atom Editor. It's important for you to keep your code clean because it makes it easier for other developers to read and it's a good habit to have. You can read more [here](https://google.github.io/styleguide/htmlcssguide.html) and [here](https://www.smashingmagazine.com/2008/11/12-principles-for-keeping-your-code-clean/).

**Comment by jesspetrillo** [comment]
Looking at this right now. Thanks!
