### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by davecastlevania** [jessorellanes/colmar-academy#4]
Great job with this project. You did an excellent job with making this your own by giving it some flair and I see you had no problems with flexbox or using responsive queries. I see that you're still building your images out which is fine. Also, if you want to really challenge yourself I would try adding separate pages to this site and linking them together so that you can show it off for a portfolio. Overall, great job with this.

Grade: Beyond expectations

**Comment by jesspetrillo** [comment]
Thanks a lot Dave. I till have a lot of work to to do but I'm glad to have received your feedback to be more clear on the direction I should take.
